import { describe, it, expect } from "vitest";
import { generateHTMLReport } from "../../src/lib/reportGenerator";
import type { AssetInfo, ValidationResult } from "../../src/types/asset";

const mockAsset: AssetInfo = {
  fileName: "hero.glb",
  filePath: "/models/hero.glb",
  fileSize: 2_500_000,
  format: "glb",
  polyCount: 12500,
  vertexCount: 8300,
  meshCount: 3,
  textures: [],
  missingTextures: [],
};

const mockValidation: ValidationResult = {
  overall: "good",
  items: [
    { label: "Tris", value: "12.5K", severity: "good", category: "geometry" },
    { label: "Non-manifold", value: "Clean", severity: "good", category: "topology" },
  ],
  groups: [
    {
      category: "geometry",
      label: "Geometry",
      items: [{ label: "Tris", value: "12.5K", severity: "good", category: "geometry" }],
    },
    {
      category: "topology",
      label: "Topology",
      items: [{ label: "Non-manifold", value: "Clean", severity: "good", category: "topology" }],
    },
  ],
};

describe("generateHTMLReport", () => {
  const html = generateHTMLReport(mockAsset, mockValidation);

  it("returns a string containing <!DOCTYPE html>", () => {
    expect(html).toContain("<!DOCTYPE html>");
  });

  it("contains the asset file name", () => {
    expect(html).toContain("hero.glb");
  });

  it("contains the asset format", () => {
    expect(html).toContain("glb");
  });

  it('contains "AssetBox" brand', () => {
    expect(html).toContain("AssetBox");
  });

  it('contains "Validation Report"', () => {
    expect(html).toContain("Validation Report");
  });

  it("contains category group labels", () => {
    expect(html).toContain("Geometry");
    expect(html).toContain("Topology");
  });

  it("contains severity colors for items", () => {
    // #4ade80 = good, #fbbf24 = warning, #f87171 = bad
    expect(html).toContain("#4ade80");
  });

  it("uses warning color for warning severity", () => {
    const warningValidation: ValidationResult = {
      overall: "warning",
      items: [{ label: "Tris", value: "50K", severity: "warning", category: "geometry" }],
      groups: [
        {
          category: "geometry",
          label: "Geometry",
          items: [{ label: "Tris", value: "50K", severity: "warning", category: "geometry" }],
        },
      ],
    };
    const warningHtml = generateHTMLReport(mockAsset, warningValidation);
    expect(warningHtml).toContain("#fbbf24");
  });

  it("uses bad color for bad severity", () => {
    const badValidation: ValidationResult = {
      overall: "bad",
      items: [{ label: "Tris", value: "200K", severity: "bad", category: "geometry" }],
      groups: [
        {
          category: "geometry",
          label: "Geometry",
          items: [{ label: "Tris", value: "200K", severity: "bad", category: "geometry" }],
        },
      ],
    };
    const badHtml = generateHTMLReport(mockAsset, badValidation);
    expect(badHtml).toContain("#f87171");
  });

  it('contains "Generated by AssetBox" footer', () => {
    expect(html).toContain("Generated by AssetBox");
  });
});
